name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  manual:
    name: Check docs up to date
    runs-on: docker
    steps:
    - name: Run apt-get update
      run: apt-get update
    - name: Install pip
      run: apt-get install -y python3 python3-pip python3-venv python-is-python3
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Make virtualenv
      run: python -m venv sphinx-env
    - name: Install docs requirements
      run: |
        source sphinx-env/bin/activate
        cd docs
        pip install -r requirements.txt
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
    - name: Remove old docs
      run: rm -r docs/source/reference/std
    - name: Run the doc generation
      run: cargo run -- doc docs/source/reference/std
    - name: Build the docs
      run: |
        source sphinx-env/bin/activate
        cd docs
        make html
    - name: Check whether the docs are outdated
      run: git diff --exit-code
  
  test:
    name: test (${{ matrix.rust }}, ${{ matrix.args }})
    runs-on: docker
    strategy:
      matrix:
        rust: [1.89.0, stable, beta, nightly]
        args: ["--no-default-features", "", "--all-features"]
        target: [x86_64-unknown-linux-gnu]
    steps:
    - name: Run apt-get update
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get update
    - name: Install musl
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get install -y musl-dev
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ matrix.target }}
    - run: cargo build --target=${{ matrix.target }} --verbose ${{ matrix.args }}
    - run: cargo test --target=${{ matrix.target }} --verbose ${{ matrix.args }}

  test-musl:
    name: test-musl (${{ matrix.args }})
    runs-on: docker
    strategy:
      matrix:
        rust: [stable]
        args: ["--no-default-features", "", "--all-features"]
        target: [x86_64-unknown-linux-musl]
    steps:
    - name: Run apt-get update
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: apt-get update
    - name: Install musl
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: apt-get install -y musl-dev
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        targets: ${{ matrix.target }}
    - run: cargo build --target=${{ matrix.target }} --verbose ${{ matrix.args }}
    - run: cargo test --target=${{ matrix.target }} --verbose ${{ matrix.args }}

  examples:
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    - run: |
        set -e
        for example in examples/*.rs; do
          filename=${example#"examples/"}
          name=${filename%".rs"}
          cargo run --example $name
        done;

  clippy:
    name: clippy (${{ matrix.args }})
    runs-on: docker
    strategy:
      matrix:
        # Test with no features, default features ("") and all features.
        # Ordered fewest features to most features.
        args: ["--no-default-features", "", "--all-features"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - run: cargo clippy --all ${{ matrix.args }}

  fmt:
    name: fmt
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - run: cargo fmt --all --check

  spelling:
      name: Spell Check with Typos
      runs-on: docker
      steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.42.0

  doc:
    name: Check rustdoc warnings
    runs-on: docker
    strategy:
      matrix:
        # Test with no features, default features ("") and all features.
        # Ordered fewest features to most features.
        args: ["--no-default-features", "", "--all-features"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run rustdoc
      run: RUSTDOCFLAGS="-D warnings" cargo doc ${{ matrix.args }}

  cargo-deny:
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: https://github.com/EmbarkStudios/cargo-deny-action@v2
      with:
        # We don't check advisories
        command: check bans licenses sources

  cargo-shear:
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    - name: Install cargo-binstall
      uses: https://github.com/cargo-bins/cargo-binstall@main
    - name: Install cargo-shear
      run: cargo binstall --no-confirm cargo-shear
    - name: Run cargo-shear
      run: cargo shear

  miri:
    name: Test with MIRI
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        components: miri
    - name: Run MIRI
      run: MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test

  valgrind:
    name: Test with Valgrind
    runs-on: docker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Rust
      uses: https://github.com/dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    - name: Run apt-get update
      run: apt-get update
    - name: Install Valgrind
      run: apt-get install -y valgrind
    - name: Install cargo-valgrind
      run: cargo install cargo-valgrind
    - name: Run Valgrind
      run: VALGRINDFLAGS="--suppressions=valgrind_suppressions.supp" cargo valgrind test --all-targets -- {{TEST}}
