//! Information generated by the type checker

use std::{collections::HashMap, fmt::Debug};

use crate::{
    ast::Identifier,
    ice,
    mir::{Ty, TyRef},
    parser::meta::MetaId,
    typechecker::types::TypeName,
};

use super::{
    expr::ResolvedPath,
    scope::{
        DeclarationKind, ResolvedName, ScopeGraph, ScopeRef, TypeOrStub,
    },
    types::{
        Function, IntKind, IntSize, Primitive, Signature, Type,
        TypeDefinition,
    },
    unionfind::UnionFind,
};

/// The output of the type checker that is used for lowering
#[derive(Clone, Default)]
pub struct TypeInfo {
    /// The unionfind structure that maps type variables to types
    pub(super) unionfind: UnionFind,

    pub ty_pool: crate::mir::Pool,

    /// All declarations in the program, extracted from the scope graph
    pub scope_graph: ScopeGraph,

    /// Map from type names to types
    pub(super) types: HashMap<ResolvedName, TypeDefinition>,

    /// The types we inferred for each Expr
    ///
    /// This might not be fully resolved yet.
    pub(super) expr_types: HashMap<MetaId, Type>,

    /// The fully qualified (and hence unique) name for each identifier.
    pub(super) resolved_names: HashMap<MetaId, ResolvedName>,

    /// Scopes of functions
    pub(super) function_scopes: HashMap<MetaId, ScopeRef>,

    /// The function that is called on each function call
    pub(super) function_calls: HashMap<MetaId, Function>,

    pub(super) function_signatures: HashMap<MetaId, Signature>,

    /// The ids of all the `Expr::Access` nodes that should be interpreted
    /// as enum variant constructors.
    pub(super) path_kinds: HashMap<MetaId, ResolvedPath>,

    pub(super) diverges: HashMap<MetaId, bool>,
}

impl TypeInfo {
    pub fn new() -> Self {
        Self::default()
    }
}

impl TypeInfo {
    pub fn resolved_name(
        &self,
        x: impl Into<MetaId> + Debug,
    ) -> ResolvedName {
        self.resolved_names[&x.into()]
    }

    pub fn function_signature(&self, x: impl Into<MetaId>) -> Signature {
        self.function_signatures[&x.into()].clone()
    }

    pub fn type_of(&mut self, x: impl Into<MetaId> + Debug) -> Type {
        let ty = self.expr_types[&x.into()].clone();
        self.resolve(&ty)
    }

    pub fn diverges(&mut self, x: impl Into<MetaId>) -> bool {
        self.diverges[&x.into()]
    }

    pub fn function(&self, x: impl Into<MetaId>) -> &Function {
        &self.function_calls[&x.into()]
    }

    pub fn function_scope(&self, x: impl Into<MetaId>) -> ScopeRef {
        self.function_scopes[&x.into()]
    }

    pub fn path_kind(&self, x: impl Into<MetaId>) -> &ResolvedPath {
        &self.path_kinds[&x.into()]
    }

    pub fn full_name(&self, name: &ResolvedName) -> Identifier {
        let mut s = self.scope_graph.print_scope(name.scope);
        s.push('.');
        s.push_str(name.ident.as_str());
        s.into()
    }

    pub fn is_numeric_type(&mut self, ty: &Type) -> bool {
        let ty = self.resolve(ty);
        match ty {
            Type::FloatVar(_) | Type::IntVar(_, _) => true,
            Type::Name(name) => {
                let type_def = self.resolve_type_name(name.name);
                type_def.is_float() || type_def.is_int()
            }
            _ => false,
        }
    }

    pub fn is_int_type(&mut self, ty: &Type) -> bool {
        self.get_int_type(ty).is_some()
    }

    pub fn get_int_type(&mut self, ty: &Type) -> Option<(IntKind, IntSize)> {
        let ty = self.resolve(ty);
        match ty {
            Type::IntVar(_, _) => Some((IntKind::Signed, IntSize::I32)),
            Type::Name(name) => {
                let type_def = self.resolve_type_name(name.name);
                if let TypeDefinition::Primitive(Primitive::Int(kind, size)) =
                    type_def
                {
                    Some((kind, size))
                } else {
                    None
                }
            }
            _ => None,
        }
    }

    pub fn is_list_type(&mut self, ty: &Type) -> bool {
        let ty = self.resolve(ty);
        match ty {
            Type::Name(name) => {
                let type_def = self.resolve_type_name(name.name);
                matches!(type_def, TypeDefinition::List(_))
            }
            _ => false,
        }
    }

    pub fn resolve_type_name(
        &mut self,
        name: ResolvedName,
    ) -> TypeDefinition {
        let dec = self.scope_graph.get_declaration(name);
        let DeclarationKind::Type(TypeOrStub::Type(ty)) = dec.kind else {
            ice!()
        };
        ty
    }

    pub fn resolve_ref<'a>(&'a self, mut t: &'a Type) -> &'a Type {
        if let Type::Var(x)
        | Type::IntVar(x, _)
        | Type::FloatVar(x)
        | Type::RecordVar(x, _) = t
        {
            t = self.unionfind.find_ref(*x);
        }

        t
    }

    pub fn resolve(&mut self, t: &Type) -> Type {
        let mut t = t.clone();

        if let Type::Var(x)
        | Type::IntVar(x, _)
        | Type::RecordVar(x, _)
        | Type::FloatVar(x) = t
        {
            t = self.unionfind.find(x).clone();
        }

        t
    }

    pub fn convert(&mut self, ty: &Type) -> TyRef {
        let ty = self.resolve(ty);
        let ty = match ty {
            Type::Var(_) => return TyRef::NEVER,
            Type::ExplicitVar(e) => ice!("Cannot convert {e}"),
            Type::Never => return TyRef::UNIT,
            Type::Function(_, _) => todo!(),
            Type::IntVar(_, _) => return TyRef::I32,
            Type::FloatVar(_) => return TyRef::F64,
            Type::Record(items) | Type::RecordVar(_, items) => {
                let items = items
                    .iter()
                    .map(|(n, t)| (n.node, self.convert(t)))
                    .collect();
                Ty::Record(items)
            }
            Type::Unit => Ty::Unit,
            Type::Name(TypeName { name, arguments }) => {
                let type_def = self.resolve_type_name(name);
                match type_def {
                    TypeDefinition::Enum(type_name, enum_variants) => {
                        let subs: Vec<_> = type_name
                            .arguments
                            .iter()
                            .zip(&arguments)
                            .collect();

                        let variants = enum_variants
                            .iter()
                            .map(|variant| {
                                let variant = variant.substitute_many(&subs);
                                let tys = variant
                                    .fields
                                    .iter()
                                    .map(|ty| self.convert(ty))
                                    .collect();
                                (variant.name, tys)
                            })
                            .collect();

                        Ty::Enum(variants)
                    }
                    TypeDefinition::Record(type_name, fields) => {
                        let subs: Vec<_> = type_name
                            .arguments
                            .iter()
                            .zip(&arguments)
                            .collect();

                        let fields = fields
                            .into_iter()
                            .map(|(ident, ty)| {
                                let ty = ty.substitute_many(&subs);
                                let ty = self.convert(&ty);
                                (ident.node, ty)
                            })
                            .collect();

                        Ty::Record(fields)
                    }
                    TypeDefinition::Runtime(_, type_id) => {
                        Ty::Runtime(type_id)
                    }
                    TypeDefinition::Primitive(p) => Ty::Primitive(p),
                    TypeDefinition::List(_type_name) => {
                        let inner = &arguments[0];
                        let inner = self.convert(inner);
                        Ty::List(inner)
                    }
                }
            }
        };
        self.ty_pool.intern(ty)
    }
}
