use std::{alloc::Layout, ptr::NonNull};

type T = ();
pub type CtxPtr = *mut ();

/// A Roto clone function
///
/// This function is generated by the Roto compiler and cannot be created manually
/// this means that they will never access the context pointer. A null pointer is
/// therefore a valid value for that parameter.
pub type CloneFn = unsafe extern "C" fn(*mut T, CtxPtr, *const T);

/// A Roto drop function
///
/// This function is generated by the Roto compiler and cannot be created manually
/// this means that they will never access the context pointer. A null pointer is
/// therefore a valid value for that parameter.
pub type DropFn = unsafe extern "C" fn(CtxPtr, NonNull<T>);

#[derive(Clone, Debug)]
#[repr(C)]
pub struct VTable {
    pub layout: Layout,
    pub clone_fn: Option<CloneFn>,
    pub drop_fn: Option<DropFn>,
}
